	$(document).ready(function(){
		$(".tops").click(function(){
			window.location.href="model.html"; 
		});
		$(".datum").click(function(){
			window.location.href="message.html";
		});
		$(".myEvaluate").click(function(){
			window.location.href="pinglun.html"; 
		});
		$(".myAdvice").click(function(){
			window.location.href="zixun.html"; 
		});
		$(".myCollect").click(function(){
			window.location.href="shoucang.html"; 
		});
		$(".safety").click(function(){
			window.location.href="integral.html"; 
		});
		$(".number").click(function(){
			window.location.href=""; 
		});
		$(".administration").click(function(){
			window.location.href="order.html"; 
		});
		$(".news").click(function(){
			window.location.href="news.html"; 
		});
	});
				